"""empty message

Revision ID: f3fa6bde0db5
Revises: 
Create Date: 2023-07-17 08:44:23.177884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3fa6bde0db5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Icomes',
    sa.Column('id_income', sa.String(length=36), nullable=False),
    sa.Column('income', sa.Integer(), nullable=True),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_income')
    )
    op.create_table('Outcomes',
    sa.Column('id_outcome', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.Integer(), nullable=True),
    sa.Column('keterangan', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_outcome')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Outcomes')
    op.drop_table('Icomes')
    # ### end Alembic commands ###
